export const corporateNavyTheme = {
  id: 'corporate-navy',
  name: 'Corporate Navy',
  description: 'Professional navy blue for business',
  preview: {
    headerGradient: 'from-gray-900 to-gray-800',
    backgroundColor: 'from-black to-gray-900',
    cardBackground: 'bg-black',
    accentColor: 'bg-yellow-400',
    textColor: 'text-yellow-200',
  },
  styles: {
    pageBackground: 'bg-gradient-to-br from-black to-gray-900 text-yellow-200',
    cardContainer: 'bg-black rounded-xl shadow-2xl border border-yellow-600 p-6',
    header: 'bg-gradient-to-b from-gray-900 to-black h-40 flex flex-col items-center justify-center',
    avatar: 'w-36 h-36 rounded-full object-cover border-4 border-yellow-500 shadow-xl',
    avatarFallback: 'w-36 h-36 rounded-full bg-gray-800 flex items-center justify-center text-yellow-400 text-4xl font-bold border-4 border-yellow-500 shadow-xl',
    title: 'text-3xl font-bold text-yellow-300 tracking-wide text-center',
    subtitle: 'text-md text-yellow-500 text-center',
    bioContainer: 'p-4 bg-gray-900 rounded-lg border border-yellow-600',
    bioText: 'text-yellow-200 leading-relaxed text-center',
    contactItem: 'flex flex-col items-center gap-2 p-4 bg-transparent rounded-lg border border-yellow-600 transition group',
    contactItemHover: 'hover:bg-gray-800',
    contactIcon: 'w-14 h-14 rounded-full border border-yellow-500 flex items-center justify-center transition text-yellow-400 text-3xl',
    contactIconHover: 'group-hover:bg-yellow-600 group-hover:text-black',
    contactLabel: 'text-xs font-semibold text-yellow-600 uppercase tracking-wide',
    contactValue: 'text-yellow-300 font-medium',
    socialButton: 'flex flex-col items-center gap-2 px-4 py-4 bg-transparent rounded-lg border border-yellow-600 transition group',
    socialButtonHover: 'hover:bg-gray-800 hover:border-yellow-400',
    actionButton: 'flex items-center justify-center gap-3 bg-yellow-500 text-black px-6 py-4 rounded-lg transition font-semibold',
    actionButtonHover: 'hover:bg-yellow-400',
    qrContainer: 'p-8 bg-gray-900 rounded-lg border border-yellow-600',
  },
};
