import type { CardTheme } from './types';

export const natureGreenTheme: CardTheme = {
  id: 'nature-green',
  name: 'Nature Green',
  description: 'Fresh and organic with green tones',
  preview: {
    headerGradient: 'from-emerald-600 to-teal-700',
    backgroundColor: 'from-emerald-50 to-teal-50',
    cardBackground: 'bg-white',
    accentColor: 'bg-emerald-600',
    textColor: 'text-slate-900',
  },
  styles: {
    pageBackground: 'bg-gradient-to-br from-emerald-50 to-teal-50',
    cardContainer: 'bg-white rounded-2xl shadow-xl',
    header: 'bg-gradient-to-r from-emerald-600 to-teal-700 h-32',
    avatar: 'w-32 h-32 rounded-full object-cover border-4 border-white shadow-lg',
    avatarFallback: 'w-32 h-32 rounded-full bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center text-white text-4xl font-bold border-4 border-white shadow-lg',
    title: 'text-4xl font-bold text-slate-900',
    subtitle: 'text-xl text-slate-600',
    bioContainer: 'p-6 bg-emerald-50 rounded-xl',
    bioText: 'text-slate-700 leading-relaxed text-center',
    contactItem: 'flex items-center gap-4 p-4 bg-emerald-50 rounded-xl transition group',
    contactItemHover: 'hover:bg-emerald-100',
    contactIcon: 'w-12 h-12 rounded-lg bg-emerald-100 flex items-center justify-center transition text-emerald-600',
    contactIconHover: 'group-hover:bg-emerald-200',
    contactLabel: 'text-xs font-medium text-slate-500 uppercase',
    contactValue: 'text-slate-900',
    socialButton: 'flex items-center gap-2 px-4 py-3 bg-emerald-50 rounded-lg transition group border border-emerald-200',
    socialButtonHover: 'hover:bg-emerald-100',
    actionButton: 'flex items-center justify-center gap-3 bg-emerald-600 text-white px-6 py-4 rounded-xl transition font-medium',
    actionButtonHover: 'hover:bg-emerald-700',
    qrContainer: 'p-8 bg-emerald-50 rounded-xl',
  },
};
